name = "litecky-decap-oauth"
main = "src/index.ts"
compatibility_date = "2025-09-22"
compatibility_flags = ["nodejs_compat"]
account_id = "13eb584192d9cefb730fde0cfd271328"

# The worker will be available at:
# https://litecky-decap-oauth.verlyn13.workers.dev

# Optional custom domain (configure in Cloudflare dashboard after deployment)
# routes = [
#   { pattern = "cms-auth.liteckyeditingservices.com/*", custom_domain = true }
# ]

[vars]
ENVIRONMENT = "production"