backend:
  name: github
  repo: verlyn13/liteckyeditingservices
  branch: main
  base_url: https://cms-auth.liteckyeditingservices.com
  auth_endpoint: /api/auth

media_folder: public/images/uploads
public_folder: /images/uploads

editor:
  preview: true

site_url: https://liteckyeditingservices.com
display_url: https://liteckyeditingservices.com

collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: src/content/pages
    create: false
    slug: '{{slug}}'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Body, name: body, widget: markdown }
      - label: SEO
        name: seo
        widget: object
        collapsed: true
        fields:
          - { label: Meta Title, name: metaTitle, widget: string, required: false }
          - { label: Meta Description, name: metaDescription, widget: text, required: false }
          - { label: No Index, name: noindex, widget: boolean, default: false }

  - name: services
    label: Services
    label_singular: Service
    folder: src/content/services
    create: true
    slug: '{{slug}}'
    summary: '{{title}} - Order: {{order}}'
    sortable_fields: ['order', 'title']
    fields:
      - { label: Title, name: title, widget: string, hint: 'Service name (e.g., Substantive Editing)' }
      - { label: Description, name: description, widget: text, hint: 'Brief 1-2 sentence description for listings' }
      - { label: Price, name: price, widget: string, required: false, hint: 'e.g., Starting at $0.04/word' }
      - label: Features
        name: features
        widget: list
        hint: 'Key features of this service - one per line'
        field: { label: Feature, name: feature, widget: string }
      - { label: Display Order, name: order, widget: number, default: 0, value_type: int, min: 0, hint: 'Lower numbers appear first' }
      - { label: Detailed Description, name: body, widget: markdown, hint: 'Full service description (supports formatting)' }

  - name: testimonials
    label: Testimonials
    label_singular: Testimonial
    folder: src/content/testimonials
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{author}} - {{role}}'
    sortable_fields: ['date', 'featured', 'author']
    fields:
      - { label: Quote, name: quote, widget: text, hint: 'The testimonial text from the client' }
      - { label: Author Name, name: author, widget: string, hint: 'Full name or "Anonymous"' }
      - { label: Role/Title, name: role, widget: string, hint: 'e.g., "PhD Candidate, History"' }
      - { label: University, name: university, widget: string, required: false, hint: 'Optional institution name' }
      - label: Rating
        name: rating
        widget: select
        default: '5'
        options: ['1', '2', '3', '4', '5']
        hint: '5-star rating scale'
      - { label: Featured on Homepage, name: featured, widget: boolean, default: false, hint: 'Show this testimonial on the homepage' }
      - { label: Date Received, name: date, widget: datetime, hint: 'When this testimonial was received' }

  - name: faq
    label: FAQ
    label_singular: Question
    folder: src/content/faq
    create: true
    slug: '{{slug}}'
    summary: '{{question}}'
    sortable_fields: ['category', 'order']
    view_groups:
      - label: Category
        field: category
    fields:
      - { label: Question, name: question, widget: string, hint: 'The frequently asked question' }
      - { label: Answer, name: answer, widget: markdown, hint: 'Detailed answer (supports formatting)' }
      - label: Category
        name: category
        widget: select
        default: 'General'
        options:
          - { label: 'General Questions', value: 'General' }
          - { label: 'Our Services', value: 'Services' }
          - { label: 'The Process', value: 'Process' }
          - { label: 'Pricing & Payment', value: 'Pricing' }
          - { label: 'Security & Privacy', value: 'Security' }
        hint: 'Group this question by topic'
      - { label: Display Order, name: order, widget: number, default: 0, value_type: int, min: 0, hint: 'Lower numbers appear first within category' }

  - name: settings
    label: Settings
    files:
      - name: general
        label: General Settings
        file: src/data/settings.json
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Description, name: siteDescription, widget: text }
          - { label: Contact Email, name: contactEmail, widget: string }
          - { label: Phone Number, name: phoneNumber, widget: string, required: false }
          - label: Social Links
            name: socialLinks
            widget: object
            fields:
              - { label: LinkedIn, name: linkedin, widget: string, required: false }
              - { label: Twitter, name: twitter, widget: string, required: false }

      - name: navigation
        label: Navigation
        file: src/data/navigation.json
        fields:
          - label: Main Menu
            name: mainMenu
            widget: list
            fields:
              - { label: Label, name: label, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Order, name: order, widget: number }