backend:
  name: github
  repo: verlyn13/liteckyeditingservices
  branch: main
  base_url: https://litecky-decap-oauth.jeffreyverlynjohnson.workers.dev
  auth_endpoint: /auth

publish_mode: editorial_workflow

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: pages
    label: Pages
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body",  name: "body",  widget: "markdown" }
