name: e2e-visual

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  visual:
    runs-on: ubuntu-latest
    env:
      CI: true
      VISUAL_POLICY: no-gutter
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Install system fonts for consistent rendering
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-dejavu-core \
            fonts-dejavu-extra \
            fonts-liberation \
            fonts-noto-core \
            fonts-noto-color-emoji \
            fonts-roboto \
            fonts-inter

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Free port 4321 if in use
        run: |
          if lsof -i:4321; then lsof -ti:4321 | xargs kill -9 || true; fi

      - name: Run visual tests (@visual)
        run: pnpm test:visual

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
