name: Infisical → Cloudflare (Production)

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (do not apply changes)'
        type: boolean
        default: true
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Infisical CLI
        run: curl -sSfL https://cli.infisical.com/install.sh | sh

      - name: Export prod secrets from Infisical
        env:
          INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
          INFISICAL_PROJECT_ID: ${{ vars.INFISICAL_PROJECT_ID }}
          INFISICAL_ENV: ${{ vars.INFISICAL_ENV }}
          INFISICAL_API_URL: ${{ secrets.INFISICAL_API_URL }}
        run: |
          mkdir -p .out
          ~/.infisical/bin/infisical export \
            --projectId "$INFISICAL_PROJECT_ID" \
            --env "${INFISICAL_ENV:-production}" \
            --format dotenv \
            --include-imports \
            > .out/prod.secrets.env
          # Split PUBLIC_ variables
          grep -E '^PUBLIC_' .out/prod.secrets.env > .out/prod.public.env || true
          # Mask values
          while IFS='=' read -r k v; do
            [ -z "$k" ] && continue; echo "::add-mask::$v"; done < .out/prod.secrets.env

      - name: Prepare Cloudflare env files
        run: |
          chmod +x scripts/secrets/cloudflare_prepare_from_infisical.sh
          ./scripts/secrets/cloudflare_prepare_from_infisical.sh .out/prod.secrets.env .out/prod.public.env

      - name: Sync to Cloudflare Pages (Production)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          CF_PAGES_PROJECT: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          DRY_RUN: ${{ inputs.dry_run }}
        run: |
          echo "Dry run: ${DRY_RUN}"
          if [ "$DRY_RUN" = "true" ]; then
            echo "Skipping apply per dry_run=true"; exit 0; fi
          # Variables (PUBLIC_*)
          while IFS='=' read -r k v; do
            [ -z "$k" ] && continue
            npx wrangler pages project variable put "$CF_PAGES_PROJECT" "$k" --value "$v"
          done < .out/prod.public.env
          # Secrets (non-PUBLIC)
          grep -vE '^PUBLIC_' .out/prod.secrets.env | while IFS='=' read -r k v; do
            [ -z "$k" ] && continue
            echo -n "$v" | npx wrangler pages project secret put "$CF_PAGES_PROJECT" "$k" --quiet
          done

