name: Quality Gate

on:
  pull_request:
    paths-ignore:
      - '_archive/**'
      - '**/*.md'
      - 'docs/**'
  push:
    branches: [main]

jobs:
  validate-structure:
    name: Validate Repository Structure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate structure and paths
        run: pnpm run validate:all

      - name: Check repository structure
        run: node scripts/validate/repo-structure.mjs

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Biome check
        run: pnpm run biome:check

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build project
        run: pnpm build

      - name: Create Sentry release and upload source maps
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
          version: ${{ github.sha }}
          sourcemaps: ./dist
          url_prefix: ~/
          finalize: true
          set_commits: auto
          ignore_empty: true

      # Note: Add `pnpm exec playwright install chromium` here when E2E tests are enabled

      - name: Verify wrangler version
        run: pnpm exec wrangler --version

  docs-gate:
    name: Documentation Gate
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Check documentation updates
        run: node scripts/gates/require-docs.mjs
        env:
          GITHUB_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
